- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 28800 #Imperial role timers
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  skills:
  - skillBotany
  - skillBaseMed
  - skillBaseConstraction
  - skillPiloting
  - skillBasicAtmos
  - skillAtmos
  - skillInstrumentation
  - skillHardInstrumentation
  - skillMaintenance
  - skillMediumConstruction
  - skillHacking

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
