- type: job
  id: Coroner
  name: job-name-coroner
  description: job-description-coroner
  playTimeTracker: JobCoroner
  psychosisGainResist: 1 # psychosis
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400 #Imperial role timers
  startingGear: CoronerGear
  icon: "JobIconCoroner"
  supervisors: job-supervisors-medicine
  canBeAntag: true
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: CoronerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCoroner
    #back: ClothingBackpackMedicalFilled
    pocket1: Paper
    shoes: ClothingShoesColorBlack
    mask: ClothingMaskSterile
    head: ClothingHeadHatSurgcapGreen
    id: CoronerPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtCoroner
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled

- type: jobIcon
  parent: JobIcon
  id: JobIconCoroner
  icon:
    sprite: /Textures/Imperial/Roles/Medical/Coroner/job_icon.rsi
    state: Coroner

- type: entity
  id: SpawnPointCoroner
  parent: SpawnPointPassenger
  name: coroner
  components:
  - type: SpawnPoint
    job_id: Coroner
  - type: Sprite
    layers:
      - state: green
      - state: coroner

- type: playTimeTracker
  id: JobCoroner

