- type: job
  id: Clown
  name: job-name-clown
  description: job-description-clown
  playTimeTracker: JobClown
  startingGear: ClownGear
  # Imperial role timers Start
  requirements:
    - !type:RoleTimeRequirement
      role: JobMime
      time: 3600
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200
  # Imperial role timers End
  icon: "JobIconClown"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      clumsyDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

- type: startingGear
  id: ClownGear
  equipment:
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder
    id: ClownPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampClown
    - CrayonRainbow
